name=HDrive
version=1.1.0
author=Jesús Amezquita, Kame Electronics
maintainer=Jesús Amezquita <l25290382@cdguzman.tecnm.mx>
sentence=H Bridge architecture based driver controller.
paragraph=Library for controlling nearly any motor driver based on an H Bridge architecture, being 100% compatible with independent two channel PWM, emergency brake and freerun.
category=Device Control
url=https://github.com/JesRex700/HDrive
architectures=*

